[General]
recentFileList=/home/a_nyone/apps/openscad/laptop_stand_0.scad, /home/a_nyone/apps/openscad/laptop_stand.scad

[design]
autoReload=true

[view]
hide3DViewToolbar=false
hideConsole=false
hideCustomizer=true
hideEditor=false
hideEditorToolbar=false
hideErrorLog=false
orthogonalProjection=false
showAxes=true
showScaleProportional=true
