preload = /home/a_nyone/Pictures/wallpapers/pink-mecha.png

wallpaper {
    monitor = eDP-1
    path = /home/a_nyone/Pictures/wallpapers/pink-mecha.png
    fit_mode = cover
}


wallpaper {
    monitor = DP-2
    path = /home/a_nyone/Pictures/wallpapers/pink-mecha.png
    fit_mode = cover
}
