preload = /home/a_nyone/Pictures/wallpapers/trees.png

wallpaper {
    monitor = eDP-1
    path = /home/a_nyone/Pictures/wallpapers/trees.png
    fit_mode = cover
}


wallpaper {
    monitor = DP-2
    path = /home/a_nyone/Pictures/wallpapers/trees.png
    fit_mode = cover
}

splash = false
