source = /home/a_nyone/.cache/wal/colors-hyprland.conf


background {
    monitor =
    path = /home/a_nyone/Pictures/wallpapers/trees.png   # only png supported for now
    color = $color1

    blur_size = 2
    blur_passes = 0 # 0 disables blurring
    noise = 0.0117
    contrast = 1.3000 # Vibrant!!!
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# Time (Hours:Minutes:Seconds)
label {
    monitor =
    # Если хочешь без секунд, убери :%S
    text = cmd[update:1000] echo "<b>$(date +"%H:%M:%S")</b>"
    color = $color6
    font_size = 70
    font_family = Roboto
    shadow_passes = 0
    position = 0, 100
    halign = center
    valign = center
}


# Greeting
label {
    monitor =
    text = hey, a_nyone!
    color = $color7
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 15
    halign = center
    valign = center
}




input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3

    dots_size = 0.26 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.64 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rouding = -1

    rounding = 22
    outer_color = $color0
    inner_color = $color0
    font_color = $color6
    fade_on_empty = true
    placeholder_text = <i>Password... </i> # Text rendered in the input box when it's empty.

    position = 0, 120
    halign = center
    valign = bottom
}

label {
    monitor =
    # Эта команда обрезает полное название раскладки до первых двух букв и переводит в верхний регистр
    text = cmd[update:1000] echo "$(hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .active_keymap' | cut -c1-2 | tr '[:upper:]' '[:lower:]')"
    color = $color7
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    
    # Позиционирование:
    position = 0, 80
    halign = center        # Центрируем относительно экрана
    valign = bottom     
}

