general {
    lock_cmd = pidof hyprlock || hyprlock       # что запускать для блокировки
    before_sleep_cmd = loginctl lock-session    # блокировать ПЕРЕД сном
    after_sleep_cmd = hyprctl dispatch dpms on  # включить монитор после просыпания
    ignore_dbus_inhibit = false                  # игнориует активные процессы и зсатвляет ноут уходить в спячку 
    ignore_systemd_inhibit = false
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session           # блокируем экран
}


listener {
    timeout = 780
    on-timeout = systemctl suspend 
    on-resume = hyprctl dispatch dpms on
}

