#btop theme file for Everforest Dark Medium

theme[main_bg]="#272e33"
theme[main_fg]="#d3c6aa"

theme[title]="#a7c080"
theme[hi_fg]="#a7c080"
theme[selected_bg]="#475258"
theme[selected_fg]="#d3c6aa"
theme[inactive_fg]="#7a8478"
theme[graph_text]="#83c092"

theme[meter_bg]="#343f44"
theme[proc_misc]="#83c092"
theme[cpu_box]="#7fbbb3"
theme[mem_box]="#a7c080"
theme[net_box]="#dbbc7f"
theme[proc_box]="#d699b6"
theme[div_line]="#475258"

theme[temp_start]="#a7c080"
theme[temp_mid]="#dbbc7f"
theme[temp_end]="#e67e80"

theme[cpu_start]="#83c092"
theme[cpu_mid]="#7fbbb3"
theme[cpu_end]="#d699b6"

theme[free_start]="#a7c080"
theme[free_mid]="#83c092"
theme[free_end]="#7fbbb3"

theme[cached_start]="#dbbc7f"
theme[cached_mid]="#d699b6"
theme[cached_end]="#e67e80"

theme[available_start]="#a7c080"
theme[available_mid]="#83c092"
theme[available_end]="#7fbbb3"

theme[used_start]="#e67e80"
theme[used_mid]="#dbbc7f"
theme[used_end]="#d699b6"

theme[download_start]="#83c092"
theme[download_mid]="#7fbbb3"
theme[download_end]="#a7c080"

theme[upload_start]="#d699b6"
theme[upload_mid]="#e67e80"
theme[upload_end]="#dbbc7f"

theme[process_start]="#a7c080"
theme[process_mid]="#83c092"
theme[process_end]="#7fbbb3"
